### ISSUE TITLE
Latest Ignorance release (1.3.9.2) is missing

### ISSUE THREAD

**Issue by alesmasiar** [TCROC/Ignorance-UPM#3] opened 2020-11-21 09:55 UTC
Hi,

The release is from 3 days and ago and since the repo should be running nightly, I think it should've already been here.

Anyways, I like that somebody ported Ignorance to UPM ... wish Mirror itself would do the same.

Thanks 👍

**Comment by TCROC** [comment] 2020-11-21 16:58
Hey @alesmasiar glad you are enjoying the UPM port!  Thanks for pointing out the issue.  I'll get right on fixing that :)

**Comment by TCROC** [comment] 2020-11-21 16:59
![image](https://user-images.githubusercontent.com/24307049/99882770-fa838200-2bf0-11eb-8a36-9c7129fd237f.png)

Looks like I turned off the nightly builds while I was doing some development on the pipeline and forgot to turn them back on.  I'll just uncomment that code and we should be good to go

**Comment by TCROC** [comment] 2020-11-21 17:29
@alesmasiar I just ran it and the tag appears to have been made successfully.  Let me know if it works for you.

**Comment by TCROC** [comment] 2020-11-22 18:36
I'm going to close this issue now as it appears to be resolved.  Let me know if you have any problems with it.

**Comment by alesmasiar** [comment] 2020-11-23 06:26
Sorry, I didn't actually have the opportunity to test it out yet, but thanks a lot, it seems to be fixed now. I appreciate the prompt response.

**Comment by alesmasiar** [comment] 2020-11-23 06:33
Actually, I've tried this right now and it seems that the release is visible on Github, but UPM in Unity still pulls 1.3.9-pre1 as latest. The tagged version link is not working for me either.

**Comment by TCROC** [comment] 2020-11-24 14:18
Hey @alesmasiar I'm reopening the issue.  I'll take a look at it this afternoon and see if I can reproduce what you are seeing.  What version of Unity are you using?

**Comment by TCROC** [comment] 2020-11-24 14:21
And also, what are you using to manage your git upm dependencies?  I'm using https://github.com/mob-sakai/UpmGitExtension

**Comment by alesmasiar** [comment] 2020-11-24 14:24
I've tried in 2019.4.14f1 and 2020.1.6f1. I'm not using the Git Extension, just plain Unity Package Manager. Old versions (before 1.3.9.2) seem to be working fine though.

**Comment by TCROC** [comment] 2020-11-24 14:31
![image](https://user-images.githubusercontent.com/24307049/100106952-25f7ae00-2e37-11eb-8655-ea42fd23c96b.png)

I was able to reproduce the issue.  It looks like Unity is really picky over what upm packages are versioned as in their manifest.json file.  It has to be SemVer compatible which from that message I'm guesing is limited to #.#.#-{someString}.  So I'll update the nightly pipeline to take any trailing #s (in this case the '.2' 1.3.9.2) and convert the "." to a "-".  So this release number will get converted from 1.3.9.2 to 1.3.9-2.  I'll get around to it this afternoon and let you know when the fix is up.

**Closed as completed** 2020-11-24 18:53 UTC

**Comment by TCROC** [comment] 2020-11-24 18:57
Hey @alesmasiar I think it is fixed now.  I tested in 2019.4.3f1 with tag 1.3.9-2 (equivalent to 1.3.9.2).  Let me know if it works for you.

**Comment by alesmasiar** [comment] 2020-11-25 07:45
Yes, the 1.3.9-2 tag is working. Thanks for the fix 👍
